# Generated by Django 5.0.3 on 2024-03-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, db_column='ClientName', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('xero_id', models.CharField(blank=True, db_column='XeroID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('xero_id', models.CharField(blank=True, db_column='XeroID', max_length=255, null=True)),
                ('general_labour', models.BooleanField(blank=True, db_column='GeneralLabour', default=False)),
                ('traffic_controller', models.BooleanField(blank=True, db_column='TrafficController', default=False)),
                ('first_aider', models.BooleanField(blank=True, db_column='FirstAider', default=False)),
                ('construction_cleaner', models.BooleanField(blank=True, db_column='ConstructionCleaner', default=False)),
                ('boom_lift', models.BooleanField(blank=True, db_column='BoomLift', default=False)),
                ('telehandler', models.BooleanField(blank=True, db_column='Telehandler', default=False)),
                ('forklift_driver', models.BooleanField(blank=True, db_column='ForkliftDriver', default=False)),
                ('hoister_driver', models.BooleanField(blank=True, db_column='HoisterDriver', default=False)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('job_role_id', models.AutoField(db_column='JobRoleID', primary_key=True, serialize=False)),
                ('role_description', models.CharField(blank=True, db_column='RoleDescription', max_length=255, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_1_5x', models.DecimalField(blank=True, db_column='Rate1_5x', decimal_places=2, max_digits=10)),
                ('rate_2x', models.DecimalField(blank=True, db_column='Rate2x', decimal_places=2, max_digits=10, null=True)),
                ('travel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_1_5x', models.DecimalField(blank=True, db_column='Pay1_5x', decimal_places=2, max_digits=10, null=True)),
                ('pay_2x', models.DecimalField(blank=True, db_column='Pay2x', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'jobRoles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(db_column='JobID', primary_key=True, serialize=False)),
                ('po_name', models.CharField(blank=True, db_column='POName', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, db_column='ClientID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.client')),
                ('job_role', models.ForeignKey(blank=True, db_column='JobRoleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(db_column='InvoiceID', primary_key=True, serialize=False)),
                ('role_description', models.TextField(blank=True, db_column='RoleDescription', null=True)),
                ('due_date', models.DateField(blank=True, db_column='DueDate', null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('worked_hours', models.DecimalField(blank=True, db_column='WorkedHours', decimal_places=2, max_digits=10, null=True)),
                ('invoice_total', models.DecimalField(blank=True, db_column='InvoiceTotal', decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(blank=True, db_column='JobID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.job')),
            ],
            options={
                'db_table': 'invoices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('job_assignment_id', models.AutoField(db_column='JobAssignmentID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, db_column='StartTime', null=True)),
                ('finish_time', models.TimeField(blank=True, db_column='FinishTime', null=True)),
                ('lunch_hours', models.DecimalField(blank=True, db_column='LunchHours', decimal_places=1, max_digits=3, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
                ('job', models.ForeignKey(blank=True, db_column='JobID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.job')),
                ('job_role', models.ForeignKey(blank=True, db_column='JobRoleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobrole')),
            ],
            options={
                'db_table': 'jobAssignments',
                'managed': True,
            },
        ),
    ]
