# Generated by Django 5.0.3 on 2024-03-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
