# Generated by Django 5.0.3 on 2024-03-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_job_options_alter_job_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('HOTNSW', 'HOT NSW'), ('NSW', 'NSW'), ('QLD', 'QLD'), ('VIC', 'VIC'), ('WA', 'WA')], max_length=50),
        ),
    ]
