# Generated by Django 5.0.3 on 2024-03-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_job_options_remove_job_job_role_jobrole_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
