# Generated by Django 5.0.3 on 2024-03-31 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_job_options_alter_job_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='job_role',
            field=models.ForeignKey(blank=True, db_column='JobRoleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobrole'),
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
