# Generated by Django 5.0.3 on 2024-03-31 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_jobrole_job_job_job_role_alter_job_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_role',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='job',
            field=models.ForeignKey(db_column='JobID', default=1, on_delete=django.db.models.deletion.CASCADE, to='website.job'),
            preserve_default=False,
        ),
    ]
