# Generated by Django 5.0.3 on 2024-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_job_job_role_jobrole_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='rate_1_5x',
            field=models.DecimalField(blank=True, db_column='Rate1_5x', decimal_places=2, max_digits=10, null=True),
        ),
    ]
