# Generated by Django 5.0.3 on 2024-04-01 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_jobrole_pay_alter_jobrole_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='employee',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='website.employee'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='job',
            field=models.ForeignKey(db_column='JobID', default=2, on_delete=django.db.models.deletion.CASCADE, to='website.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='job_role',
            field=models.ForeignKey(db_column='JobRoleID', on_delete=django.db.models.deletion.CASCADE, to='website.jobrole'),
        ),
    ]
